### ISSUE TITLE
Put under curosr instead of taking fullscreen

### ISSUE THREAD

**Issue by tmpm697** [ggVGc/fzf_browser#6]
When surf through files/folder, is there a way to use current cursor position instead of clear and use the whole screen?

e.g:
```
> ls
> hola!
>fzf_browser   <---- trigger fzf here instead of clear two above commands for fzf_browser to use
> whoami
```

**Comment by ggVGc** [comment]
The current implementation is based heavily on fzf (which does not support this afaik), and it's all basically a gigantic bash hack that I made as an experiment.
I have for a long time intended to rewrite this in something more general purpose, and make it possible to use different UIs for the actual fuzzy matching.
Unfortunately it has been working fairly well for me, and I haven't had the time to revisit this project yet.
The feature you're after is supported by fzy (https://github.com/jhawthorn/fzy), but I think practically everything in this script would need to be rewritten for fzy, so it'd amount to the rewrite mentioned above.

**Comment by tmpm697** [comment]
@ggVGc fzf can be able to do fuzzy search at command line instead of taking whole screen, but I tried with your pluign and failed to have trigger fzf_browser under current prompt.

**Comment by ggVGc** [comment]
How do you do this with fzf? I have checked the documentation in the past (and just did again) and I can't find an option to do it. I have always believed this is one of the main reasons people pick `fzy` over `fzf`.

**Comment by tmpm697** [comment]
This is what I try to mention, fzf won't take fullscreen in this case:

![image](https://i.imgur.com/Fc2PIfu.png)

**Comment by ggVGc** [comment]
Okay, I figured it out. fzf takes a `height` argument, which controls this feature.
To use it with `fzf_browser`, you can pass `fzf` options directly with the `-f` flag.
Example: `fuzzybrowse -f "--height=30%"`

**Comment by tmpm697** [comment]
@ggVGc : Somehow I failed to get that, would you do a PR for it?

**Comment by ggVGc** [comment]
No PR should be necessary. It should just work with this command: `fuzzybrowse -f "--height=30%"`.
Does that not show you the fzf interface inline?
