### ISSUE TITLE
Error on selection with file previews

### ISSUE THREAD

**Issue by veilm** [ggVGc/fzf_browser#8]
After installing with
```sh
cd # ~
git clone https://github.com/ggVGc/fzf_browser
PATH=$PATH:$HOME/fzf_browser # Temporary; for this shell instance
```
and then running ``fuzzybrowse`` as shown in the README, I get a blank screen instead of seeing my files and directories:
![temp](https://user-images.githubusercontent.com/57649592/180463327-d5ceb288-b235-463f-83b7-6fc294160a88.png)

``/home/michael``, however, is not empty:
```sh
$ ls -1 /home/michael
forgot
fzf_browser
hidden
keep_forgot
media
pending
src
sync
temp.png
test
```

The usage line ``fuzzybrowse [options] root_path`` makes it seem like specifying the root path is required, so I tried ``fuzzybrowse .`` as well, but it had the same result. Although the shell I'm running it from shouldn't matter because you specify bash through the shebang, I tried running it from both oksh and bash, both of which had the same result. My operating system is Arch Linux, in case that's relevant.

fzf version:
```sh
$ fzf --version
0.29.0 (dc975e8)
```

Did I misunderstand the usage/installation instructions?

**Comment by veilm** [comment]
I skimmed through the code and it looks like the project uses ``fd`` instead of ``find`` or ``ls`` for getting files and directories. I didn't have this installed, which was causing this issue. ``fd`` should probably be listed in the README as a dependency or the program should catch it in advance.

**Comment by veilm** [comment]
Now, my selection screen looks like
![temp](https://user-images.githubusercontent.com/57649592/180466250-04f8b329-2f97-4afa-8e02-60221615e2c0.png)
(which seems different from that of the gifs in the README) and selecting anything gives me an error. For example, if I select temp.png, the program quits and prints
```
/home/michael/fzf_browser/fzf_browser.sh: line 427: cd: ./fzf_browser// ./LICENSE.md | ./README.md | ./fuzzybrowse | .: No such file or directory
./fzf_browser.sh\ \|\ .
./hidden
./media/\ .
./pending/\ .
./src
./sync/\ .
./forgot
./keep_forgot
```

**Comment by veilm** [comment]
Update: I realize now that I was using Tab for navigation, which I forgot started selecting multiple items. Selecting it properly, I am now able to successfully select normal files and switch to directories that don't have any file previews. Going for the fzf_browser directory, for example, outputs
```
/home/michael/fzf_browser/fzf_browser.sh: line 427: cd: ./fzf_browser// ./LICENSE.md | ./README.md | ./fuzzybrowse | .: No such file or directory
./fzf_browser.sh\ \|\ .
```

**Comment by veilm** [comment]
Line 427 of fzf_browser.sh is
```sh
printf "%q" "$(cd "$(dirname "$1")"; pwd)$base"
```
Adding
```sh
echo dirname "$1" >> ~/log
echo "$1" >> ~/log
```
below it, I see
```sh
$ cat ~/log
dirname /home/michael
/home/michael
dirname ./fzf_browser// ./LICENSE.md | ./README.md | ./fuzzybrowse | ./fzf_browser.sh | .
./fzf_browser// ./LICENSE.md | ./README.md | ./fuzzybrowse | ./fzf_browser.sh | .
```

I don't really know how fzf_browser works internally, but I'd assume that the file previews (``./LICENSE.md | ./README.md | ./fuzzybrowse | ./fzf_browser.sh | .``) are supposed to be stripped before sending them to dirname and cd, which isn't happening.

Additionally, I'm seeing a lot of ``./`` and ``//``, which I don't see in the README gifs. Is something going wrong there too?

**Comment by veilm** [comment]
(My interest in fzf_browser was unrelated to its actual usage, so I don't really care about the solution)

**Comment by ggVGc** [comment]
Hi, thanks for the interest, and sorry you had some problems :)
This project is quite a hacky beast I threw together in a fairly short time many years ago, but I still actively use, and it's been on my long list of TODO to clean it up, preferably reimplementing it in something proper to get around all the environment dependencies.
This issue, and several others are also affecting me, but I have started avoiding selecting directories like this rather than making time to fix it...
It appeared at some point during a system upgrade and I'm not entirely sure what changed. It might be the case that I accidentally introduced it, but I don't believe that's the case.
Either way, one day I might make time to work on this, and fix things!
